name: Java Tests

on:
  push:
    paths:
      - 'backend/data-analyzer/**'
      - '.github/workflows/java.yml'
    branches: [ main, develop ]
  pull_request:
    paths:
      - 'backend/data-analyzer/**'
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/data-analyzer

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'oracle'
        cache: 'maven'
    
    - name: Build and test
      run: mvn -B verify
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./backend/data-analyzer/target/site/jacoco/jacoco.xml
        flags: java
        fail_ci_if_error: true